apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-volume
  namespace: fpsa
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: {{storage}}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-volume-claim
  namespace: fpsa
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fpsa
spec:
  selector:
    matchLabels:
      app: fpsa-backend
      tier: backend
  replicas: 1
  template:
    metadata:
      name: fpsa-backend
      namespace: fpsa
      labels:
        app: fpsa-backend
        tier: backend
    spec:
      volumes:
        - name: backend-storage
          persistentVolumeClaim:
            claimName: backend-volume-claim
      containers:
      - name: fpsa-backend
        image: svfpsa/backend:{{backend_version}}
        volumeMounts:
          - mountPath: {{storage}}
            name: backend-storage
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: DB_HOST
          value: mariadb
        - name: DB_PORT
          value: 3306
        - name: DB_USER
          value: "{{db_user}}"
        - name: DB_PASSWORD
          value: "{{db_password}}"
        - name: DB_NAME
          value: fpsa
        - name: JWT_SECRET
          value: "{{JWT_SECRET}}"
        - name: COOKIE_SECRET
          value: "{{COOKIE_SECRET}}"
        - name: env
          value: PRODUCTION
        - name: URL_SITE
          value: "https://fpsa.nl/"
        - name: SENDGRID_APIKEY
          value: "{{sendgrid_password}}"
        - name: STORAGE_PATH
          value: "{{storage}}"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fpsa
spec:
  type: NodePort
  selector:
    app: fpsa-backend
    tier: backend
  ports:
    - port: 3000
