apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume-claim
  namespace: fpsa
  finalizers: null
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: database-volume
  resources:
    requests:
      storage: 3Gi