apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-volume
  namespace: fpsa
  finalizers: []
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: {{.Values.storagePath}}