apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-volume-claim
  namespace: fpsa
  finalizers: null
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-volume
  resources:
    requests:
      storage: 3Gi