apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-volume
  namespace: fpsa
  labels:
    app: {{ .Chart.Name }}-volume
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: {{.Values.storagePath}}