name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@master

# Build and test project
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build

# Dockerize project
    - name: Docker login
      env:
        Username: ${{secrets.DOCKER_USERNAME}}
        Password: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $Username -p $Password
    
    - name: Docker build
      run: docker build -t svfpsa/backend:$GITHUB_SHA -f Dockerfile .;
    
    - name: Docker publish
      run: docker push svfpsa/backend:$GITHUB_SHA

# Deploy container
    - name: Deploy
      uses: 'deliverybot/helm@master'
      with:
        release: 'fpsa-api'
        namespace: 'fpsa'
        chart: 'k8b'
        helm: 'helm3'
        token: '${{ github.token }}'
        values: |
          tag: $GITHUB_SHA
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
