name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@master

# Build and test project
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build
# Dockerize project
    - name: Docker login
      run: docker login -u {{secrets.DOCKER_USERNAME}} -p {{secrets.DOCKER_PASSWORD}}
    
    - name: Docker build
      run: docker build -t svfpsa/site --pull -f Dockerfile .;
    
    - name: Docker publish
      run: docker run -d svfpsa/site;

# Deploy container
#     - name: templater make runnable
#       run: chmod +x .github/workflows/templater.sh
    
#     - name: Build template
#       run: .github/workflows/templater.sh template.yaml > filledin.yaml
    
#     - name: deploy to cluster
#       uses: steebchen/kubectl@master
#       env:
#         KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#       with:
#         args: apply -f filledin.yaml
