name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@master

# Build and test project
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build
    - run: npm run test --if-present
    
    - name: Read package.json
      uses: tyankatsu0105/read-package-version-actions@v1
      id: package-version

# Dockerize project
    - name: Docker login
      env:
        Username: ${{secrets.DOCKER_USERNAME}}
        Password: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $Username -p $Password
    
    - name: Docker build
      run: docker build -t svfpsa/site:${{ steps.package-version.outputs.version }} --pull -f Dockerfile .;
    
    - name: Docker publish
      run: docker push svfpsa/site:${{ steps.package-version.outputs.version }}

# Deploy container
    - name: templater make runnable
      run: chmod +x .github/workflows/templater.sh
    
    - name: Build template
      env:
        DB_USER: ${{secrets.DB_USER}}
        DB_PW: ${{secrets.DB_PW}}
        Cookie_secret: ${{secrets.COOKIE_SECRET}}
        JWT_SECRET: ${{secrets.JWT_SECRET}}
        Sendgrid: ${{secrets.SENDGRID}}
        storage_path: ${{secrets.STORAGE}}
      run: db_user=$DB_USER db_password=$DB_USER JWT_SECRET=$Jwt_secret COOKIE_SECRET=$Cookie_secret sendgrid_password=$Sendgrid storage=$storage_path .github/workflows/templater.sh template.yaml > filledin.yaml
    
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: apply -f filledin.yaml
