name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@master

# Build and test project
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build
# Dockerize project

# Deploy container
    - name: templater make runnable
      run: chmod +x .github/workflows/templater.sh
    
#    - name: deploy to cluster
#      uses: steebchen/kubectl@master
#      env:
#        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
#      with:
#        args: create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node
