name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@master

# Build and test project
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install packages
      run: npm i

    - name: build project
      run: npm run build

# Dockerize project
    - name: Docker login
      run: docker login docker.pkg.github.com -u bastiaanv -p ${{ secrets.GITHUB_TOKEN }}
    
    - name: Docker build
      run: docker build -t docker.pkg.github.com/federation-purple-study-associations/fpsa-api/backend:$GITHUB_SHA -f Dockerfile .;
    
    - name: Docker publish
      run: docker push docker.pkg.github.com/federation-purple-study-associations/fpsa-api/backend:$GITHUB_SHA

# Deploy container
    - name: Deploy
      uses: elseu/sdu-helm-deploy-action@0.0.5
      with:
        release: 'fpsa-api'
        namespace: 'fpsa'
        chart: 'k8b'
        helm: 'helm3'
        timeout: 2m30s
        token: '${{ github.token }}'
        values: |
          tag: '${{ github.sha }}'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
